name = "domain-admin"
pages_build_output_dir = "dist"
compatibility_date = "2025-11-24"

[[d1_databases]]
binding = "DB"
database_name = "domain-admin-db"
database_id = "98faca15-8152-40f3-9270-b1b020571c17"
